version: '3.9'
  
services:
  app:
    build:
      context: ./src
    container_name: app
    command: bash -c "npm install && wait-for db:3306 -t 40 -- npm start"
    volumes:
      - ./src/:/src/app
    depends_on:
      - db

  nginx:
    container_name: nginx_app
    build: 
      context: ./nginx
    ports:
      - 8080:80
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
    - ./initdb:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root